### ISSUE TITLE
gnome-shell 3.34.1 no data arriving

### ISSUE THREAD

**Issue by liviynz** [profy12/gnome-shell-netatmo-station#1]
I see in the netatmo api page it's created a listing for it  so it's connecting (it must have the right login details) but no temperatures show up in the extension.

**Comment by maxencelaurent** [comment]
same here. I got these logs:

```
JS ERROR: TypeError: this._display.getNetatmoData is not a function
_parseData@~/..../extension.js:100:9
_initToken/<@~/.../extension.js:58:46
```
PR is coming
